config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'

  #ルーティングを一括して自動生成
  #onlyで生成するルーティングを限定
  resources :music_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :music_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :music_image
  
end

app/models/music_comment.rb
class MusicComment < ApplicationRecord

  belongs_to :user
  belongs_to :music_image

end

app/models/music_image.rb
class MusicImage < ApplicationRecord
  
  #MusicImageモデルからuser_idに関連付けしてUserモデルの参照を可能にする。
  #今回MusicImageモデルに関連付けられるのは１つのUserモデルのみのため、単数形。
  belongs_to :user
  
  #画像アップ用のメソッド、フィールド名にimageを指定
  attachment :image
  
  # has_many :favorites, dependent: destroy
  has_many :music_comments, dependent: :destroy
  
  validates :music_name, presence: true
  validates :image, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :music_images, dependent: :destroy
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #refile記述
  attachment :profile_image

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end

#※presenseですが、falseにしないと新規登録時に作用してintroductionがnilとなって新規登録できなくなりますので注意してください。新規登録時に自己紹介も入力必要な場合とするならtrueでOKです
validates :introduction, presence: false, length: { maximum: 50 } # 自己紹介の最高文字数は50文字

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #ログインしていない場合、ログイン画面へ
  before_action :authenticate_user!, except: [:top]
  
  #configure~ → deviceで利用できるパラメーターを設定しますよという意味
  #before_action　→ 全てのコントローラーの実行前にアクションさせる
  #:devise_controller? → もしそれがdeviseのコントローラーだったら（devise_controller?というメソッドの返り値がtrueだったら）configure_permitted_parametersを呼ぶ。
  before_action :configure_permitted_parameters, if: :devise_controller?

  #ログイン後、投稿一覧画面に遷移させる
  def after_sign_in_path_for(resource)
    music_images_path
  end


  protected

  #ここの記述ではデバイス版のストロングパラメーター。
  #デバイスでは初期設定でメールアドレスとパスワードしか許されていない。
  #ここを編集することでユーザーネームなどを入れることができる。
  #今回の例だとnameカラムへの保存を許可する。
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    music_image = MusicImage.find(params[:music_image_id])
    favorite = current_user.favorites.new(music_image_id: music_image.id)
    favorite.save
    redirect_to music_image_path(music_image)
  end

  def destroy
    music_image = MusicImage.find(params[:music_image_id])
    favorite = current_user.favorites.find_by(music_image_id: music_image.id)
    favorite.destroy
    redirect_to music_image_path(music_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/music_comments_controller.rb
class MusicCommentsController < ApplicationController

  def create
    music_image = MusicImage.find(params[:music_image_id])
    comment = current_user.music_comments.new(music_comment_params)
    comment.music_image_id = music_image.id
    comment.save
    redirect_to music_image_path(music_image)
  end

  def destroy
    MusicComment.find_by(id: params[:id]).destroy
    redirect_to music_image_path(params[:music_image_id])
  end


  private

  def music_comment_params
    params.require(:music_comment).permit(:comment)
  end


end

app/controllers/music_images_controller.rb
class MusicImagesController < ApplicationController

  def new
    #インスタンス変数に空のインスタンスを渡して画像の投稿を可能にする
    @music_image = MusicImage.new
  end

  #投稿データの保存
  def create
    #music_image_paramsでフォームで入力されたデータが投稿データとして許可されているパラメータかどうかをチェック
    @music_image = MusicImage.new(music_image_params)
    #ログイン中のユーザー情報の取得（deviceのヘルパーメソッド）
    @music_image.user_id = current_user.id
    if @music_image.save
      redirect_to music_images_path
    else
      render :new
    end
  end

  #投稿データの一覧表示
  #kaminari専用のpageメソッドを追加
  def index
    @music_images = MusicImage.page(params[:page]).reverse_order
  end

  def show
    #ルーティングはroutes.rbで定義しているためアクションメソッドのみ
    @music_image = MusicImage.find(params[:id])
    @music_comment = MusicComment.new
  end
  
  def edit
    @music_image = MusicImage.find(params[:id])
  end

  def destroy
    @music_image = MusicImage.find(params[:id])
    @music_image.destroy
    redirect_to music_image_path
  end


  def update
    music_image = MusicImage.find(params[:id])
    music_image.update(music_image_params)
    redirect_to music_image_path(music_image)
  end

  #投稿データのストロングパラメータ
  private

  def music_image_params
    params.require(:music_image).permit(:music_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ユーザーのデータを1件取得し、インスタンス変数へ渡す。
  #kaminariのpageメソッドを使用
  def show
    @user = User.find(params[:id])
    @music_images = @user.music_images.page(params[:page]).reverse_order
  end
  
  #編集用viewでform_withを使用するためparams[:id]でユーザ情報を取得して@userに保存し
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/music_comments_helper.rb
module MusicCommentsHelper
end

app/helpers/music_images_helper.rb
module MusicImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<!--#メイン画像とロゴ部分-->
<div class="top">
  <div style="position: relative; display:inline-block;">
  <%= image_tag 'top.jpeg' %>
  <p><%= image_tag 'logo-transparent.png' %>
    <button type="button" class="btn btn-outline-light"><%= link_to "新規登録", new_user_registration_path %></button>
    <button type="button" class="btn btn-outline-light"><%= link_to "ログイン", new_user_session_path %></button>
  </p>

</div>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="jp">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="style.css">
  <script src="https://use.fontawesome.com/926fe18a63.js"></script>
  <title>Document</title>
</head>
<body>
  <footer>
    <div class="container">
      <!--<nav class="footB">-->
      <!--  <ul>-->
      <!--    <li><a href="https://yotamatsumaru.jp/blog/used_car_1/">TOP</a></li>-->
      <!--  </ul>-->
      <!--</nav>-->
      <div class="footA">
        <div class="foot_img">
          <p><%= image_tag 'logo-transparent.png' %></p>
          <!--<img src="https://yotamatsumaru.jp/img/logo.png" alt="" width="250px" />-->
        </div>
      </div>
      <!--<nav class="footC">-->
      <!--  <ul>-->
      <!--    <li><a href="https://www.facebook.com/spoonkokubunji/"><span class="fa fa-facebook"></span></a></li>-->
      <!--    <li>-->
      <!--      <a href="https://twitter.com/kokubunnjispoon"><span class="fa fa-twitter"></span></a>-->
      <!--    </li>-->
      <!--  </ul>-->
      <!--</nav>-->
  </footer>
  <script src="./app.js"></script>
</body>
</html>

app/views/layouts/_header.html.erb
<header>
<script src="https://kit.fontawesome.com/36d386a37b.js" crossorigin="anonymous"></script>
    <!--<div class="hamburger">-->
    <!--  <span></span>-->
    <!--  <span></span>-->
    <!--  <span></span>-->
    <!--</div>-->
    
    <!--<nav class="globalMenuSp">-->
    <!--<ul>-->

<!--#画面が大きければコンテンツ表示、小さくするとプラグのレスポンシブナビバー-->
    <nav class="navbar navbar-expand-lg navbar-info bg-info">
      <div class="container">
<div id="head-logo">
    <%= link_to image_tag('/images/logo-transparent.png'), '/music_images' %>
</div><!-- head-logo -->
        <!--<span>-->
        <!--  <#= link_to "Music match", root_path, class:"navbar-brand" %>-->
        <!--</span>-->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to "マイページ", user_path(current_user), class:"fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to "投稿", new_music_image_path, class:"fas fa-users nav-link text-light" %>
              </li>
              <li>
                <%= link_to "探す", music_images_path , class:"fas fa-book-open nav-link text-light" %>
              <!--</li>-->
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %>
              </li>
            <% else %>
              <!--<li>-->
              <!--  <%#= link_to "探す", root_path, class:"fas fa-home nav-link text-light" %>-->
              <!--</li>-->
              <!--<li>-->
              <!--  <%#= link_to "About", home_about_path, class:"fas fa-link nav-link text-light" %>-->
              <!--</li>-->
              <li>
                <%= link_to "新規登録", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to "ログイン", new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music match</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--#ヘッダー部分-->
  <header>
　  <% unless current_page?(root_path) %>
    <%= render "layouts/header" %>
    <% end %>
  </header>

  <body>
    <div class="centering_parent">
      <span class="centering_item">
         <%= yield %>
      </span>
    </div>
  </body>

  <!--#フッター-->
  <footer>
    <%= render "layouts/footer" %>
  </footer>

  </body>
</html>

app/views/music_images/_list.html.erb
<!--#コントローラから渡された@post_images変数内から1つずつ取り出して、post_image変数へ格納-->
<% music_images.each do |music_image| %>
  <div class="card">
    <h3 class="card-header"><%= music_image.music_name %></h3>
      <div class="card-body">
        <div>
          <!--#link_toでmusic_image_path(music_image.id)のリンク先URLを指定する。-->
          <%= link_to music_image_path(music_image.id) do %>
  
            <!--#refile側が用意したヘルパー、 imgタグを生成(post_image変数のimage_idに保存された画像のimgタグを生成)-->
            <%#= attachment_image_tag music_image, :image, :fill, 150, 150 %>
          <% end %>
  
          <p><%= attachment_image_tag music_image.user, :profile_image, :fill, 60, 60, fallback: "music_image.jpe" %></p>
          <p><%= music_image.user.name %></p>
  
          <%# music_images.each do |music_image| %>
            <!--#refile側が用意したヘルパー、 imgタグを生成(post_image変数のimage_idに保存された画像のimgタグを生成)-->
            <%#= attachment_image_tag music_image, :image, :fill, 150, 150 %>
          <%# end %>
      
          <p><%= music_image.caption %></p>
          <!--#post_image変数のuser_idに関連付けられているuserモデルのnameカラムを表示-->
          <p><%= link_to "#{music_image.music_comments.count} コメント", music_image_path(music_image.id) %>
          
      <%= link_to '詳細', music_image_path(music_image.id), method: :get %>
      <%#= link_to '編集', edit_music_image_path(music_image.id), method: :get %>
          
        </div>
      </div>
  </div>
<% end %>


<!--#kaminariでページャ実装のためのヘルパー-->
<%= paginate @music_images %>

app/views/music_images/index.html.erb
<h1>募集一覧</h1>

<h4>一緒に演奏する仲間を探しましょう！
</h4>

<!--#部分テンプレートの呼び出し-->
<%= render 'music_images/list', music_images: @music_images %>

app/views/music_images/new.html.erb
<!--#新規投稿用ページ-->

<h1>音楽投稿フォーム</h1>

<!--#エラーの内容を確認する-->
<% if @music_image.errors.any? %>
  <%= @music_image.errors.count %>件のエラーが発生しました
  <% @music_image.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @music_image, local:true do |f| %>

  <h4>イメージ画像</h4>
  <%= f.attachment_field :image %>

  <h4>タイトル</h4>
  <%= f.text_field :music_name %>

  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/music_images/show.html.erb
<!--詳細画面-->

<div>
  <%= attachment_image_tag @music_image, :image %>
    <p>タイトル : <%= @music_image.music_name %></p>
    <p>説明 : <%= @music_image.caption %></p>
    <p>ユーザーネーム : <%= @music_image.user.name %></p>
    <p>投稿日時 : <%= @music_image.created_at.strftime('%Y/%m/%d') %></p>

  <!--#ログイン中のユーザーの場合、削除ボタンを表示-->
  <% if @music_image.user == current_user %>
    <%= link_to "編集", edit_user_path(@music_image) %>
    <%= link_to "削除", music_image_path(@music_image), method: :delete %>
  <% end %>

  <!--#いいね機能-->
    <%# if @music_image.favorited_by?(current_user) %>
    <p>
      <%#= link_to music_image_favorites_path(@music_image), method: :delete do %>
      ♥<%#= @music_image.favorites.count %>いいね
    <%# end %>
    </p>
    <%# else %>
    <p>
      <%#= link to music_image_favorites_path(@music_image), method: :music do %>
      ♡<%#= @music_image.favorites.count %>いいね
    <%# end %>
    </p>
</div>

<!--#コメント機能-->
<div>
  <p>コメント件数 : <%= @music_image.music_comments.count %></p>
    <% @music_image.music_comments.each do |music_comment| %>
      <p><%= attachment_image_tag music_comment.user, :profile_image, :fill, 60, 60, fallback: "music_image.jpeg" %></p>
        <%= music_comment.user.name %>
        <%= music_comment.created_at.strftime('%Y/%m/%d') %>
        <%= music_comment %>
        <% if music_comment.user == current_user %>
    <div>
      <%= link_to "削除", music_image_music_comment_path(music_comment.music_image, music_comment), method: :delete %>
    </div>
  <% end %>
<% end %>
</div>

<div>
  <%= form_with(model:[@music_image, @music_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for = "inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <!--#プロフィール画像表示、画像選択用ボタン-->
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "music_image.jpeg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>

  <!--#自己紹介-->
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介" %>

  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<!--#ユーザーのプロフィール部分-->

プロフィール

<div>
  <h3><%= @user.name %></h3>
  <!--#プロフィール画像の表示-->
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "music_image.jpeg" %>
  <h3><%= @user.introduction %></h3>

  <!--#編集ページへのリンク-->
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>


あなたの投稿
<!--#部分テンプレートの呼び出し-->
<%= render 'music_images/list', music_images: @music_images %>